################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/

# Laptop
monitor=eDP-2,2560x1440@240,auto,1

# Monitor Screen
monitor=HDMI-A-1,1920x1080@240,auto,1

