# This is an example Hyprland config file.
# Refer to the wiki for more information.
# https://wiki.hypr.land/Configuring/

# Please note not all available settings / options are set here.
# For a full list, see the wiki

# You can split this configuration into multiple files
# Create your files separately and then link them to this file like this:
# source = ~/.config/hypr/myColors.conf

######################
### SOURCING FILES ###
######################

source = ~/.config/hypr/temp/monitors.conf
source = ~/.config/hypr/temp/programs.conf
source = ~/.config/hypr/temp/autostart.conf
source = ~/.config/hypr/temp/env.conf
source = ~/.config/hypr/temp/permissions.conf
source = ~/.config/hypr/temp/decoration.conf
source = ~/.config/hypr/temp/animations.conf
source = ~/.config/hypr/temp/windowrules.conf
source = ~/.config/hypr/temp/layout.conf
source = ~/.config/hypr/temp/misc.conf
source = ~/.config/hypr/temp/input.conf
source = ~/.config/hypr/temp/keybinds.conf

